# assumes parent folder is in this directory
bigrat: true
whitelist:
  enforce: true
  groups:
    - #group1
    - #group2
  active:
    - #group1
pack-list:
  # default pack must be named mainpack
  mainpack:
    port:
    location: #/web/__.zip
  additionalpack:
    port:
    location: #/web/__.zip
  pastel-day:
    port:
    location: #/web/__.zip
#events
sins: false
pastel-day: false

terminal-velocity-enabled: false
terminal-velocity-speed: 40