# assumes parent folder is in this directory
whitelist:
  enforce: true
  groups:
    - #group1
    - #group2
pack-list:
  # default pack must be named mainpack
  mainpack:
    port:
    location: #/web/__.zip
  additionalpack:
    port:
    location: #/web/__.zip
